[tool.poetry]
name = "repl_python3_Day-7-Hangman-5-Start-1"
version = "0.1.0"
description = ""
authors = ["VS21 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
clear = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
